name: Deploy Angular to FTPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install



  deploy:
    needs: build 

    steps:
      - name: Upload to FTPS
        uses: ncw/ftp@v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: ${{ secrets.FTP_PORT }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: dist/
          remoteDir: ${{ secrets.FTP_REMOTE_DIR }}
          protocol: ftps
          options: --implicit
