name: Deploy Angular to FTPS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Debug information
        run: |
          echo "Current directory: $(pwd)"
          echo "Node.js version: $(node --version)"
          echo "npm version: $(npm --version)"
          echo "Angular CLI version: $(ng --version)"

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: ng build --prod
