
name: testAngular App


on:

  push:

    branches:
    - main
 

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest 

 

    steps:

      - uses: actions/checkout@v3

 

      - name: Use Node.js 18.18.2

        uses: actions/setup-node@v3

        with:

          node-version: 18.18.2 

 

      - name: Install dependencies

        run: npm install  # Replace with `npm install` if you prefer

       

      - name: Install cli
        run: npm install --save-dev @angular/cli
      - name: Build the Angular app
        run: npx ng build
      - name: Upload to Azure WebApp using FTP

        uses: ercindedeoglu/ftp-transfer-action@v2

        with:

          host: ${{secrets.ENDPOINT}}
          user: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          forceSSL: true
          # Path to the "dist" folder or your custom output directory

          source: './dist/

          destination: '/site/wwwroot/'
